# INPUT
auto_userdots_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/auto_userdots"
deconvolved_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/decon"
metadata: "/media/MiSo/iFISH-singleLocus-analysis/input/2018-09-13-iFISH-singleLocus-metadata.tsv"

# OUTPUT
masks_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/cmask" # set to None to avoid storing the segmentation output
output_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/output"

# GENERAL
aspect: [300., 130., 130.]

# LAMINA DISTANCE
dilation: 5
distance_type: "center_percentile"
threads_per_job: 10
mask_prefix: "cmask_"
mask_compressed: True
mask_labeled: False
axis_fraction: 0.25
discard_channels: ["a700", "ir800"]
dilate_Z: True

# MERGE & FILTERS
metadata_delim: "\t"
k_sigma_population_selection: 3

# SAMPLES
datasets: [
  "iAM102_20180607_001"
]